[tools]
"cargo:aviutl2-cli" = "latest"
"github:karoterra/aviutl2-aulua" = "latest"
"npm:rulesync" = "latest"
stylua = "latest"

[tasks]
build = ["aulua build"]
dev = "mise watch -i scripts -d 10ms build"
